[package]
name = "binserde"
version = "0.1.0"
authors = ["Eric Seppanen <eds@reric.net>"]
edition = "2018"
resolver = "2"

[dependencies]
serde = "1.0"
bincode = "1.3"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
